defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 1200
mem_gb: 16
cpus_per_task: 8
#partition: orchid
partition: par-single
#gres: gpu:1
name: ${name}
#additional_parameters:
#  account: orchid